; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:stable]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
framework = arduino
lib_extra_dirs = ~/Arduino/libraries

;for ESP32 boards (4MB flash)
board = esp32dev
board_build.partitions = minspiff.csv
;enable max debugging 
build_flags = -DCORE_DEBUG_LEVEL=5
lib_deps = fastled/FastLED@^3.10.3

[env:stable-s3]
;this one is probably fine to attempt to keep up to date.
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
framework = arduino
lib_extra_dirs = ~/Arduino/libraries

;for ESP32-S3 boards (8MB flash)
board_build.partitions = app_s3.csv
board = esp32-s3-devkitc-1
;enable max debugging and set so that Serial is the USB port and automatically started on boot
build_flags = -DCORE_DEBUG_LEVEL=5 -D ARDUINO_USB_MODE=1 -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = fastled/FastLED@^3.10.3

[env:sans-tester]
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = 
	direct
	esp32_exception_decoder
monitor_port = /dev/ttyACM1
upload_port = /dev/ttyACM1
framework = arduino, espidf
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-c6-devkitm-1
board_build.embed_txtfiles = 
	managed_components/espressif__esp_insights/server_certs/https_server.crt
	managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
	managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
	managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt
board_build.partitions = sans-tester-partitions.csv
board_upload.offset_address = 0x180000
board_upload.flash_size = 4MB
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT -DARDUINO_USB_MODE
	-DSOC_RX0=-1 -DSOC_TX0=-1
	-DSANS_TESTER
	-DVIRTUALLED_EMULATE_FASTLED
	-DCOMPILE_VIRTUAL_LED
board_build.cmake_extra_args = 
	-DSDKCONFIG_DEFAULTS="sdkconfig.sans-tester.defaults"
lib_deps = 
	fastled/FastLED@^3.10.3
	adafruit/Adafruit SSD1306@^2.5.16